insert into menu_items (section, category, name, price, description, image, sort_order) values
  ('food', 'popular', 'Pinsa Ham', 320, 'Quests favourite - comes with spicy peppers', null, 0),
  ('food', 'popular', 'Cheeseburger', 280, 'Customer favourite - juicy beef, cheddar, lettuce & house sauce', null, 10),
  ('food', 'popular', 'Chicken Wrap', 240, 'Loaded with crispy chicken, fresh veggies & creamy sauce', null, 20),
  ('food', 'popular', 'Loaded Fries', 220, 'Crispy fries topped with cheese, bacon & special sauce', null, 30),
  ('food', 'popular', 'Chicken Wings', 260, 'Crispy wings tossed in your choice of spicy or BBQ sauce', null, 40),
  ('food', 'popular', 'Margherita Pizza', 320, 'Classic favourite - tomato sauce, mozzarella & fresh basil', null, 50),
  ('food', 'pizza', 'Margherita', 320, 'Classic tomato sauce, mozzarella, fresh basil & olive oil', null, 0),
  ('food', 'pizza', 'Pepperoni', 350, 'Tomato sauce, mozzarella & spicy pepperoni', null, 10),
  ('food', 'pizza', 'Prosciutto & Mushroom', 380, 'Mozzarella, prosciutto, mushrooms & tomato sauce', null, 20),
  ('food', 'pizza', 'Four Cheese', 390, 'Mozzarella, gorgonzola, parmesan & cheddar', null, 30),
  ('food', 'pizza', 'Diavola', 370, 'Spicy salami, mozzarella, tomato sauce & chili peppers', null, 40),
  ('food', 'pizza', 'Ham & Olives', 350, 'Mozzarella, ham, black olives & tomato sauce', null, 50),
  ('food', 'hamburgers', 'Classic Cheeseburger', 280, 'Beef patty, cheddar, lettuce, tomato, onion & house sauce', null, 0),
  ('food', 'hamburgers', 'Bacon Burger', 320, 'Beef patty, crispy bacon, cheddar, lettuce & BBQ sauce', null, 10),
  ('food', 'hamburgers', 'BBQ Double Burger', 380, 'Two beef patties, cheddar, crispy onions & smoky BBQ sauce', null, 20),
  ('food', 'hamburgers', 'Crispy Chicken Burger', 290, 'Crispy chicken fillet, lettuce, tomato & creamy garlic sauce', null, 30),
  ('food', 'hamburgers', 'Spicy Chicken Burger', 300, 'Crispy chicken, jalapeños, cheddar & spicy house sauce', null, 40),
  ('food', 'hamburgers', 'Mushroom Swiss Burger', 330, 'Beef patty, sautéed mushrooms, Swiss cheese & house sauce', null, 50),
  ('drinks', 'popular', 'Cappuccino', 120, 'Rich espresso topped with steamed milk foam', null, 0),
  ('drinks', 'popular', 'Iced Latte', 140, 'Smooth espresso over cold milk and ice', null, 10),
  ('drinks', 'popular', 'Mojito', 280, 'White rum, fresh mint, lime & soda', null, 20),
  ('drinks', 'popular', 'Hot Chocolate', 160, 'Rich Belgian chocolate topped with cream', null, 30),
  ('drinks', 'coffee', 'Espresso', 90, 'Short, strong & straight to the point', null, 0),
  ('drinks', 'coffee', 'Americano', 100, 'Espresso lengthened with hot water', null, 10),
  ('drinks', 'coffee', 'Cappuccino', 120, 'Rich espresso topped with steamed milk foam', null, 20),
  ('drinks', 'coffee', 'Flat White', 130, 'Double espresso with velvety micro-foam', null, 30),
  ('drinks', 'coffee', 'Macchiato', 110, 'Espresso "stained" with a touch of foam', null, 40),
  ('drinks', 'coffee', 'Iced Latte', 140, 'Smooth espresso over cold milk and ice', null, 50),
  ('drinks', 'cocktails', 'Mojito', 280, 'White rum, fresh mint, lime & soda', null, 0),
  ('drinks', 'cocktails', 'Aperol Spritz', 300, 'Aperol, prosecco & a splash of soda', null, 10),
  ('drinks', 'cocktails', 'Margarita', 290, 'Tequila, triple sec & fresh lime', null, 20),
  ('drinks', 'cocktails', 'Gin & Tonic', 270, 'Premium gin with a botanical tonic', null, 30),
  ('drinks', 'cocktails', 'Negroni', 310, 'Gin, vermouth & Campari, stirred not shaken', null, 40),
  ('drinks', 'cocktails', 'Piña Colada', 300, 'Rum, coconut cream & pineapple juice', null, 50),
  ('drinks', 'gallery', 'Cappuccino', 160, null, '/cappuccino.avif', 0),
  ('drinks', 'gallery', 'Iced Latte', 140, null, '/icedLatte.avif', 10),
  ('drinks', 'gallery', 'Mojito', 280, null, '/mojito.avif', 20),
  ('drinks', 'gallery', 'Hot Chocolate', 160, null, '/chocolate.avif', 30);
