// Menu content for the VOI site.
// Add or edit dishes/drinks here — the markup is generated by script.js
// (see renderMenus) from whatever data-* attributes each <section> declares.
// Prices are in Macedonian denari (ден).

const MENU_ITEMS = {
  food: {
    popular: [
    {
      name: "Margherita Pizza",
      price: 320,
      desc: "Classic Italian pizza topped with tomato sauce, mozzarella, and fresh basil"
    },
    {
      name: "Classic Cheeseburger",
      price: 280,
      desc: "Juicy beef patty with cheddar cheese, fresh lettuce, tomato, and house sauce"
    },
    {
      name: "Crispy Chicken Wrap",
      price: 240,
      desc: "Crispy chicken wrapped with fresh vegetables and creamy garlic sauce"
    },
    {
      name: "Loaded Fries",
      price: 220,
      desc: "Golden crispy fries topped with melted cheese, crispy bacon, and special sauce"
    },
    {
      name: "BBQ Chicken Wings",
      price: 260,
      desc: "Tender chicken wings coated in smoky BBQ sauce"
    },
    {
      name: "Ham & Cheese Pinsa",
      price: 320,
      desc: "Roman-style crispy pinsa topped with tomato sauce, mozzarella, ham, and oregano"
    }
  ],

  pizza: [
    {
      name: "Margherita Pizza",
      price: 280,
      desc: "Classic tomato sauce, melted mozzarella, and fresh basil on a crispy crust"
    },
    {
      name: "Pepperoni Pizza",
      price: 350,
      desc: "Traditional pizza topped with mozzarella, rich tomato sauce, and spicy pepperoni"
    },
    {
      name: "Ham & Mushroom Pizza",
      price: 340,
      desc: "A delicious combination of sliced ham, mushrooms, mozzarella, and tomato sauce"
    },
    {
      name: "Quattro Formaggi",
      price: 380,
      desc: "Creamy four-cheese pizza with mozzarella, gorgonzola, parmesan, and cheese blend"
    },
    {
      name: "BBQ Chicken Pizza",
      price: 360,
      desc: "Grilled chicken, smoky BBQ sauce, mozzarella, red onion, and fresh herbs"
    },
    {
      name: "Vegetarian Pizza",
      price: 300,
      desc: "Fresh bell peppers, mushrooms, olives, onions, mozzarella, and tomato sauce"
    }
  ],

  hamburgers: [
    {
      name: "Classic Cheeseburger",
      price: 280,
      desc: "Juicy beef patty, cheddar cheese, lettuce, tomato, pickles, and house sauce"
    },
    {
      name: "Double Smash Burger",
      price: 380,
      desc: "Two smashed beef patties with double cheddar, caramelized onions, and burger sauce"
    },
    {
      name: "Crispy Chicken Burger",
      price: 270,
      desc: "Crispy fried chicken fillet with fresh lettuce, pickles, and creamy mayo"
    },
    {
      name: "BBQ Bacon Burger",
      price: 350,
      desc: "Beef patty topped with crispy bacon, cheddar cheese, smoky BBQ sauce, and onions"
    },
    {
      name: "Spicy Jalapeño Burger",
      price: 320,
      desc: "Beef patty with pepper jack cheese, jalapeños, fresh lettuce, and spicy house sauce"
    },
    {
      name: "Classic Hamburger",
      price: 250,
      desc: "Grilled beef patty served with lettuce, tomato, onion, pickles, and signature sauce"
    }
  ]
  },

  drinks: {
    popular: [
      { name: "Cappuccino", price: 120, desc: "Rich espresso topped with steamed milk foam" },
      { name: "Iced Latte", price: 140, desc: "Smooth espresso over cold milk and ice" },
      { name: "Mojito", price: 280, desc: "White rum, fresh mint, lime & soda" },
      { name: "Hot Chocolate", price: 160, desc: "Rich Belgian chocolate topped with cream" },
    ],
    coffee: [
      { name: "Espresso", price: 90, desc: "Short, strong & straight to the point" },
      { name: "Americano", price: 100, desc: "Espresso lengthened with hot water" },
      { name: "Cappuccino", price: 120, desc: "Rich espresso topped with steamed milk foam" },
      { name: "Flat White", price: 130, desc: "Double espresso with velvety micro-foam" },
      { name: "Macchiato", price: 110, desc: 'Espresso "stained" with a touch of foam' },
      { name: "Iced Latte", price: 140, desc: "Smooth espresso over cold milk and ice" },
    ],
    cocktails: [
      { name: "Mojito", price: 280, desc: "White rum, fresh mint, lime & soda" },
      { name: "Aperol Spritz", price: 300, desc: "Aperol, prosecco & a splash of soda" },
      { name: "Margarita", price: 290, desc: "Tequila, triple sec & fresh lime" },
      { name: "Gin & Tonic", price: 270, desc: "Premium gin with a botanical tonic" },
      { name: "Negroni", price: 310, desc: "Gin, vermouth & Campari, stirred not shaken" },
      { name: "Piña Colada", price: 300, desc: "Rum, coconut cream & pineapple juice" },
    ],
    // Photo gallery on the drinks page. Note: Cappuccino is priced at 160ден here,
    // vs 120ден in the list above — kept exactly as it was in the original markup.
    gallery: [
      { name: "Cappuccino", price: 160, image: "imgs/cappuccino.avif" },
      { name: "Iced Latte", price: 140, image: "imgs/icedLatte.avif" },
      { name: "Mojito", price: 280, image: "imgs/mojito.avif" },
      { name: "Hot Chocolate", price: 160, image: "imgs/chocolate.avif" },
    ],
  },
};
