// Menu content for the VOI site.
// Add or edit dishes/drinks here — the markup is generated by script.js
// (see renderMenus) from whatever data-* attributes each <section> declares.
// Prices are in Macedonian denari (ден).

const MENU_ITEMS = {
  food: {
    popular: [
      { name: "Pinsa Ham", price: 320, desc: "Quests favourite - comes with spicy peppers" },
      { name: "Cheeseburger", price: 280, desc: "Customer favourite - juicy beef, cheddar, lettuce & house sauce" },
      { name: "Chicken Wrap", price: 240, desc: "Loaded with crispy chicken, fresh veggies & creamy sauce" },
      { name: "Loaded Fries", price: 220, desc: "Crispy fries topped with cheese, bacon & special sauce" },
      { name: "Chicken Wings", price: 260, desc: "Crispy wings tossed in your choice of spicy or BBQ sauce" },
      { name: "Margherita Pizza", price: 320, desc: "Classic favourite - tomato sauce, mozzarella & fresh basil" },
    ],
    pizza: [ 
      { name: "Margherita", price: 320, desc: "Classic tomato sauce, mozzarella, fresh basil & olive oil", }, 
      { name: "Pepperoni", price: 350, desc: "Tomato sauce, mozzarella & spicy pepperoni", }, 
      { name: "Prosciutto & Mushroom", price: 380, desc: "Mozzarella, prosciutto, mushrooms & tomato sauce", }, 
      { name: "Four Cheese", price: 390, desc: "Mozzarella, gorgonzola, parmesan & cheddar", }, 
      { name: "Diavola", price: 370, desc: "Spicy salami, mozzarella, tomato sauce & chili peppers", }, 
      { name: "Ham & Olives", price: 350, desc: "Mozzarella, ham, black olives & tomato sauce", }, 
    ], 
    hamburgers: [ 
      { name: "Classic Cheeseburger", price: 280, desc: "Beef patty, cheddar, lettuce, tomato, onion & house sauce", }, 
      { name: "Bacon Burger", price: 320, desc: "Beef patty, crispy bacon, cheddar, lettuce & BBQ sauce", },
      { name: "BBQ Double Burger", price: 380, desc: "Two beef patties, cheddar, crispy onions & smoky BBQ sauce", },
      { name: "Crispy Chicken Burger", price: 290, desc: "Crispy chicken fillet, lettuce, tomato & creamy garlic sauce", }, 
      { name: "Spicy Chicken Burger", price: 300, desc: "Crispy chicken, jalapeños, cheddar & spicy house sauce", }, 
      { name: "Mushroom Swiss Burger", price: 330, desc: "Beef patty, sautéed mushrooms, Swiss cheese & house sauce", },
    ],
  },

  drinks: {
    popular: [
      { name: "Cappuccino", price: 120, desc: "Rich espresso topped with steamed milk foam" },
      { name: "Iced Latte", price: 140, desc: "Smooth espresso over cold milk and ice" },
      { name: "Mojito", price: 280, desc: "White rum, fresh mint, lime & soda" },
      { name: "Hot Chocolate", price: 160, desc: "Rich Belgian chocolate topped with cream" },
    ],
    coffee: [
      { name: "Espresso", price: 90, desc: "Short, strong & straight to the point" },
      { name: "Americano", price: 100, desc: "Espresso lengthened with hot water" },
      { name: "Cappuccino", price: 120, desc: "Rich espresso topped with steamed milk foam" },
      { name: "Flat White", price: 130, desc: "Double espresso with velvety micro-foam" },
      { name: "Macchiato", price: 110, desc: 'Espresso "stained" with a touch of foam' },
      { name: "Iced Latte", price: 140, desc: "Smooth espresso over cold milk and ice" },
    ],
    cocktails: [
      { name: "Mojito", price: 280, desc: "White rum, fresh mint, lime & soda" },
      { name: "Aperol Spritz", price: 300, desc: "Aperol, prosecco & a splash of soda" },
      { name: "Margarita", price: 290, desc: "Tequila, triple sec & fresh lime" },
      { name: "Gin & Tonic", price: 270, desc: "Premium gin with a botanical tonic" },
      { name: "Negroni", price: 310, desc: "Gin, vermouth & Campari, stirred not shaken" },
      { name: "Piña Colada", price: 300, desc: "Rum, coconut cream & pineapple juice" },
    ],
    // Photo gallery on the drinks page. Note: Cappuccino is priced at 160ден here,
    // vs 120ден in the list above — kept exactly as it was in the original markup.
    gallery: [
      { name: "Cappuccino", price: 160, image: "cappuccino.avif" },
      { name: "Iced Latte", price: 140, image: "icedLatte.avif" },
      { name: "Mojito", price: 280, image: "mojito.avif" },
      { name: "Hot Chocolate", price: 160, image: "chocolate.avif" },
    ],
  },
};
